[wokwi]
version = 1
firmware = ".pio/build/esp32doit-devkit-v1/firmware.bin"
elf = ".pio/build/esp32doit-devkit-v1/firmware.elf"

# WiFi Configuration
[[wifi]]
ssid = "Wokwi-GUEST"
password = ""
internet = true
channel = 6    # Set WiFi channel to 6 for faster connection

# Forward http://localhost:8080 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8080"
to = "target:80"